Repository teambluemods/healthmod-forge, pull requests merged in 2021-01, with the labels that each got.

#2 update minecraft, forge, downgrade kotlin
  README.md
  gradle.properties
  src/main/resources/META-INF/mods.toml
Labels: priority:low, type:enhancement

#4 use correct package
  build.gradle
  src/main/kotlin/io/github/teambluemods/healthmod/client/HealthModClient.kt
  src/main/kotlin/io/github/teambluemods/healthmod/client/armor/FaceMaskModel.kt
  src/main/kotlin/io/github/teambluemods/healthmod/client/screen/BandageBoxScreen.kt
  src/main/kotlin/io/github/teambluemods/healthmod/common/blocks/BandageBoxBlock.kt
  src/main/kotlin/io/github/teambluemods/healthmod/common/blocks/BloodTestMachineBlock.kt
  src/main/kotlin/io/github/teambluemods/healthmod/common/container/BandageBoxContainer.kt
  src/main/kotlin/io/github/teambluemods/healthmod/common/effects/ModEffect.kt
  src/main/kotlin/io/github/teambluemods/healthmod/common/effects/WoundInfectionEffect.kt
  src/main/kotlin/io/github/teambluemods/healthmod/common/items/AntibioticsItem.kt
  src/main/kotlin/io/github/teambluemods/healthmod/common/items/BandageItem.kt
  src/main/kotlin/io/github/teambluemods/healthmod/common/items/FaceMaskItem.kt
  src/main/kotlin/io/github/teambluemods/healthmod/common/items/SyringeItem.kt
  src/main/kotlin/io/github/teambluemods/healthmod/common/tileentities/BandageBoxTileEntity.kt
  src/main/kotlin/io/github/teambluemods/healthmod/common/tileentities/BloodTestMachineTileEntity.kt
  src/main/kotlin/io/github/teambluemods/healthmod/core/HealthMod.kt
  src/main/kotlin/io/github/teambluemods/healthmod/core/config/HealthModConfig.kt
  src/main/kotlin/io/github/teambluemods/healthmod/core/config/ServerConfig.kt
  src/main/kotlin/io/github/teambluemods/healthmod/core/registries/BlockRegistries.kt
  src/main/kotlin/io/github/teambluemods/healthmod/core/registries/ContainerTypeRegistries.kt
  src/main/kotlin/io/github/teambluemods/healthmod/core/registries/EffectRegistries.kt
  src/main/kotlin/io/github/teambluemods/healthmod/core/registries/ItemRegistries.kt
  src/main/kotlin/io/github/teambluemods/healthmod/core/registries/TileEntityTypeRegistries.kt
  src/main/kotlin/io/github/teambluemods/healthmod/core/registries/VillagerProfessionRegistries.kt
  src/main/kotlin/io/github/teambluemods/healthmod/core/util/extensions/ItemStackExtensions.kt
  src/main/kotlin/io/github/teambluemods/healthmod/core/util/extensions/WorldExtensions.kt
Labels: priority:high, type:bug

#3 bandage box mechanic
  src/main/kotlin/io/github/teambluemods/healthmod/client/HealthModClient.kt
  src/main/kotlin/io/github/teambluemods/healthmod/client/screen/BandageBoxScreen.kt
  src/main/kotlin/io/github/teambluemods/healthmod/common/blocks/BandageBoxBlock.kt
  src/main/kotlin/io/github/teambluemods/healthmod/common/container/BandageBoxContainer.kt
  src/main/kotlin/io/github/teambluemods/healthmod/common/items/FaceMaskItem.kt
  src/main/kotlin/io/github/teambluemods/healthmod/common/tileentities/BandageBoxTileEntity.kt
  src/main/kotlin/io/github/teambluemods/healthmod/core/registries/ItemRegistries.kt
  src/main/kotlin/io/github/teambluemods/healthmod/core/registries/VillagerProfessionRegistries.kt
Labels: priority:medium, type:enhancement
